<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_dados-de-contato',
		'title' => 'Dados de Contato',
		'fields' => array (
			array (
				'key' => 'field_581b1c2ea07cd',
				'label' => 'Endereço',
				'name' => 'contato_endereco',
				'type' => 'textarea',
				'instructions' => 'Insira o endereço da sede da ONG',
				'default_value' => '',
				'placeholder' => 'Logradouro, complemento, CEP, cidade, estado.',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_581b1c7ea07ce',
				'label' => 'Telefone',
				'name' => 'contato_telefone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(DD) XXXX-XXXX',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_581b1cd1a07cf',
				'label' => 'E-mail de contato',
				'name' => 'contato_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => 'contato@site.org',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_581b1d23a07d0',
				'label' => 'Localização',
				'name' => 'contato_localizacao',
				'type' => 'text',
				'instructions' => 'Coloque o link direto de incorporação do Google Maps demonstrado em negrito.</br></br>Exemplo: <iframe src="<b>https://www.google.com/maps/embed?pb=!1m14!1m12!1m-49-BR!2sb2097</b>" frameborder="0" style="border:0"></iframe>',
				'default_value' => 'https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d7646.781615313749!2d-49.2597665!3d-16.60714420000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spt-BR!2sbr!4v1478177332097',
				'placeholder' => '',
				'prepend' => '<em><</em><em>iframe src="</em>',
				'append' => '" frameborder="0" style="border:0"<em>></em><em><</em><em>/iframe</em><em>></em>',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post',
					'operator' => '==',
					'value' => '290',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-evento',
		'title' => 'Dados de Evento',
		'fields' => array (
			array (
				'key' => 'field_58247d34baaf9',
				'label' => 'Imagem',
				'name' => 'evento_imagem',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_581880bf526da',
				'label' => 'Data e hora do evento',
				'name' => 'data_e_hora_evento',
				'type' => 'date_time_picker',
				'instructions' => 'Selecione a data e a hora ',
				'show_date' => 'true',
				'date_format' => 'dd/mm/yy',
				'time_format' => 'hh:mmtt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'true',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'eventos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-filme',
		'title' => 'Dados de Filme',
		'fields' => array (
			array (
				'key' => 'field_58247f4ebb32f',
				'label' => 'Capa do filme',
				'name' => 'filme_capa',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_58247f60bb330',
				'label' => 'Ficha técnica',
				'name' => 'filme_ficha_tecnica',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 20,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'filmes',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-informativo',
		'title' => 'Dados de Informativo',
		'fields' => array (
			array (
				'key' => 'field_58247eb1cb74e',
				'label' => 'Anexo',
				'name' => 'informativo_anexo',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_58247ee5cb74f',
				'label' => 'Imagem',
				'name' => 'informativo_imagem',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'informativos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-membro-de-equipe',
		'title' => 'Dados de Membro de Equipe',
		'fields' => array (
			array (
				'key' => 'field_58207af21a541',
				'label' => 'Mini-currículo',
				'name' => 'membro_curriculo',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_58207b0c1a542',
				'label' => 'E-mail',
				'name' => 'membro_mail',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_58207b4f1a543',
				'label' => 'Link lattes',
				'name' => 'membro_lattes',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'equipe',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-pesquisa',
		'title' => 'Dados de Pesquisa',
		'fields' => array (
			array (
				'key' => 'field_58247c6bd85c7',
				'label' => 'Imagem',
				'name' => 'pesquisa_imagem',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_58245cddb1cd9',
				'label' => 'Anexo',
				'name' => 'pesquisa_anexo',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pesquisas',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-producoes',
		'title' => 'Dados de Produções',
		'fields' => array (
			array (
				'key' => 'field_5824763391ace',
				'label' => 'Anexo',
				'name' => 'producoes_anexo',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'producoes',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-publicacao',
		'title' => 'Dados de Publicação',
		'fields' => array (
			array (
				'key' => 'field_5824790f70112',
				'label' => 'Capa',
				'name' => 'publicacao_capa',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5824795170113',
				'label' => 'Resumo',
				'name' => 'publicacao_resumo',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5824797270114',
				'label' => 'Editora',
				'name' => 'publicacao_editora',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5824798b70115',
				'label' => 'Público leitor',
				'name' => 'publicacao_publico',
				'type' => 'text',
				'instructions' => 'Que tipo de público é destinada essa publicação',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_582479c370116',
				'label' => 'Valor',
				'name' => 'publicacao_valor',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '30,00',
				'prepend' => 'R$',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58247a3f70117',
				'label' => 'Anexo',
				'name' => 'publicacao_anexo',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'publicacoes',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-video',
		'title' => 'Dados de Vídeo',
		'fields' => array (
			array (
				'key' => 'field_58247fccec119',
				'label' => 'Imagem',
				'name' => 'video_imagem',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_58247fdeec11a',
				'label' => 'Vídeo via Youtube',
				'name' => 'video_url',
				'type' => 'text',
				'instructions' => 'URL do vídeo do Youtube',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58248001ec11b',
				'label' => 'Vídeo via Upload',
				'name' => 'video_upload',
				'type' => 'file',
				'instructions' => 'Enviar vídeo <b>exclusivamente em formato .mp4</b>',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'videos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_dados-de-artigo',
		'title' => 'Dados de Artigo',
		'fields' => array (
			array (
				'key' => 'field_582456312180b',
				'label' => 'Quem escreveu',
				'name' => 'artigo_autor',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5824566d2180c',
				'label' => 'Data de publicação',
				'name' => 'artigo_publicacao',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_582458bc2180d',
				'label' => 'Anexo',
				'name' => 'artigo_anexo',
				'type' => 'file',
				'instructions' => 'Insira aqui o arquivo relacionado ao artigo (.pdf, .mov, .doc etc)',
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'artigos',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 2,
	));
}



?>